/// <reference types="vitest" />
// Vitest config for the Romarr SPA. Lives separate from the
// production vite.config.ts so `pnpm test` doesn't drag in
// the PWA service-worker plugin (workbox blows up under jsdom).
//
// Path aliases mirror tsconfig.json's "paths"; keep them in
// lockstep when adding a new alias.

import path from "node:path";
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}", "tests/**/*.{test,spec}.{ts,tsx}"],
    css: false,
    coverage: {
      // Spec 014 SC-006 / T129 — coverage gate ≥ 60% on the
      // critical operator paths (search, grab/import flow,
      // profiles, library). Generated by ``pnpm test:coverage``;
      // the V8 provider is faster than istanbul on the SPA's
      // mostly-tsx surface.
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/**/*.spec.{ts,tsx}",
        "src/test/**",
        "src/main.tsx",
        "src/types/**",
      ],
      thresholds: {
        // Per-glob thresholds for the SC-006 critical paths.
        // The values are pinned at current measurements (with a
        // small floor) so the gate ratchets-but-never-regresses:
        // it catches regressions today, and each follow-up slice
        // that lifts coverage on a critical path is responsible
        // for raising its threshold here. The 60% target lives
        // in the spec; the floor below is the tightening gate
        // each contributor sees on every pnpm test:coverage run.
        "src/pages/Library/index.tsx": {
          lines: 50,
          statements: 50,
          branches: 35,
          functions: 20,
        },
        "src/pages/AddNew/**/*.tsx": {
          lines: 60,
          statements: 60,
          branches: 50,
          functions: 50,
        },
        "src/pages/Settings/Profiles/index.tsx": {
          lines: 80,
          statements: 80,
          branches: 40,
          functions: 60,
        },
      },
    },
  },
});
